#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _CaDynamics_E2_reg(void);
extern void _CaT_reg(void);
extern void _Ca_HVA_reg(void);
extern void _Ca_LVAst_reg(void);
extern void _Cad_reg(void);
extern void _IL_reg(void);
extern void _Ih_reg(void);
extern void _Im_reg(void);
extern void _K_Pst_reg(void);
extern void _K_Tst_reg(void);
extern void _NMDA_reg(void);
extern void _NMDAeee_reg(void);
extern void _NMDAmajor_reg(void);
extern void _NaTa_t_reg(void);
extern void _NaTs2_t_reg(void);
extern void _Nap_Et2_reg(void);
extern void _PlateauConductance_reg(void);
extern void _SK_E2_reg(void);
extern void _SKv3_1_reg(void);
extern void _ampa_reg(void);
extern void _ca_reg(void);
extern void _epsp_reg(void);
extern void _gabaa_reg(void);
extern void _gabab_reg(void);
extern void _h_kole_reg(void);
extern void _h_migliore_reg(void);
extern void _kBK_reg(void);
extern void _kadist_reg(void);
extern void _kaprox_reg(void);
extern void _kv_reg(void);
extern void _leak_reg(void);
extern void _na_reg(void);
extern void _vecstim_reg(void);
extern void _vmax_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," \"CaDynamics_E2.mod\"");
    fprintf(stderr," \"CaT.mod\"");
    fprintf(stderr," \"Ca_HVA.mod\"");
    fprintf(stderr," \"Ca_LVAst.mod\"");
    fprintf(stderr," \"Cad.mod\"");
    fprintf(stderr," \"IL.mod\"");
    fprintf(stderr," \"Ih.mod\"");
    fprintf(stderr," \"Im.mod\"");
    fprintf(stderr," \"K_Pst.mod\"");
    fprintf(stderr," \"K_Tst.mod\"");
    fprintf(stderr," \"NMDA.mod\"");
    fprintf(stderr," \"NMDAeee.mod\"");
    fprintf(stderr," \"NMDAmajor.mod\"");
    fprintf(stderr," \"NaTa_t.mod\"");
    fprintf(stderr," \"NaTs2_t.mod\"");
    fprintf(stderr," \"Nap_Et2.mod\"");
    fprintf(stderr," \"PlateauConductance.mod\"");
    fprintf(stderr," \"SK_E2.mod\"");
    fprintf(stderr," \"SKv3_1.mod\"");
    fprintf(stderr," \"ampa.mod\"");
    fprintf(stderr," \"ca.mod\"");
    fprintf(stderr," \"epsp.mod\"");
    fprintf(stderr," \"gabaa.mod\"");
    fprintf(stderr," \"gabab.mod\"");
    fprintf(stderr," \"h_kole.mod\"");
    fprintf(stderr," \"h_migliore.mod\"");
    fprintf(stderr," \"kBK.mod\"");
    fprintf(stderr," \"kadist.mod\"");
    fprintf(stderr," \"kaprox.mod\"");
    fprintf(stderr," \"kv.mod\"");
    fprintf(stderr," \"leak.mod\"");
    fprintf(stderr," \"na.mod\"");
    fprintf(stderr," \"vecstim.mod\"");
    fprintf(stderr," \"vmax.mod\"");
    fprintf(stderr, "\n");
  }
  _CaDynamics_E2_reg();
  _CaT_reg();
  _Ca_HVA_reg();
  _Ca_LVAst_reg();
  _Cad_reg();
  _IL_reg();
  _Ih_reg();
  _Im_reg();
  _K_Pst_reg();
  _K_Tst_reg();
  _NMDA_reg();
  _NMDAeee_reg();
  _NMDAmajor_reg();
  _NaTa_t_reg();
  _NaTs2_t_reg();
  _Nap_Et2_reg();
  _PlateauConductance_reg();
  _SK_E2_reg();
  _SKv3_1_reg();
  _ampa_reg();
  _ca_reg();
  _epsp_reg();
  _gabaa_reg();
  _gabab_reg();
  _h_kole_reg();
  _h_migliore_reg();
  _kBK_reg();
  _kadist_reg();
  _kaprox_reg();
  _kv_reg();
  _leak_reg();
  _na_reg();
  _vecstim_reg();
  _vmax_reg();
}
