#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Users/tsjb2/plateau-potentials/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Users/tsjb2/plateau-potentials/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/tsjb2/Dropbox (Cambridge University)/GitHub/Network-Rhythms/mrule/plateau-potentials/mod/x86_64/.libs/libnrnmech.so" "$@"
